#!/bin/sh
# An example of a oneshot rc script.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

### BEGIN rc-info
# PROVIDES: example2
# REQUIRES: example1
# BEFORE: MULTIUSER
# TYPE: oneshot
### END rc-info

name="example2"
rcvar="${name}_enable"

# If you don't provide start_msg or stop_msg, defaults will be used.
# Also true of stop_cmd(), in both oneshot and daemonizing scripts.

start_cmd() {
	mkdir -p /tmp/example || return 1
	touch /tmp/example/hello || return 1
	rm -rf /tmp/example || return 1
}

. /etc/rc.subr
run_rc_command "$1"
