#!/bin/sh
# Example of a pseudo-target.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

### BEGIN rc-info
# PROVIDES: TARGET
# REQUIRES: example1 example2
# TYPE: oneshot
### END rc-info

name="TARGET"
rcvar="${name}_enable"
start_msg="Reached target TARGET"

start_cmd() {
	:
}

. /etc/rc.subr
run_rc_command "$1"
