#!/bin/sh
PATH=/usr/sbin:/usr/bin:/sbin:/bin
order=$(/sbin/rcorder /etc/rc.d/*)
if test $? -ne 0; then
	echo "rc: rcorder failed." >&2
	echo "Dropping to /bin/sh" >&2
	exec /bin/sh
fi
for f in $order; do
	test -x "$f" && RC_BOOT=1 "$f" start
done
