#!/bin/sh
# Invokes rc.d scripts in the order determined by rcorder(8).

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PATH=/usr/sbin:/usr/bin:/sbin:/bin
order=$(/sbin/rcorder /etc/rc.d/*)
if test $? -ne 0; then
	echo "rc: rcorder failed." >&2
	exit 1
fi
for f in $order; do
	test -x "$f" && RC_BOOT=1 "$f" start
	if test "$?" -ne 0; then
		exit 1
	fi
done
