#!/bin/sh
# Determines the order that rc.d scripts should be invoked in based on parsing their PROVIDES, REQUIRES and BEFORE fields.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# NOTE: AI was heavily used in the writing of this file.
# However, the author can assure you that this code has been thoroughly studied and tested by the author,
# and has proven to be fully functional without major bugs.
# Do note that further testing is encouraged for anybody who uses this program.

for f in "$@"; do
        provides=$(awk -F': *' '/^# PROVIDES:/{print $2}' "$f")
        requires=$(awk -F': *' '/^# REQUIRES:/{print $2}' "$f")
        before=$(awk -F': *' '/^# BEFORE:/{print $2}' "$f")
        echo "$f|${provides:-$f}|${requires}|${before}"
done | awk -F'|' '
{
	n++
	file[n] = $1
	prov[n] = $2
	req[n]  = $3
	bef[n]  = $4
}
END {
	for (i = 1; i <= n; i++) {
		pc = split(prov[i], parr, " ")
		for (k = 1; k <= pc; k++) provides[parr[k]] = file[i]
	}
	for (i = 1; i <= n; i++) {
		f = file[i]
		rc = split(req[i], rarr, " ")
		for (k = 1; k <= rc; k++)
			if (rarr[k] != "none") deps[f] = deps[f] " " rarr[k]
		bc = split(bef[i], barr, " ")
		for (k = 1; k <= bc; k++) {
			target = provides[barr[k]]
			if (target == "") continue
			ownname = (prov[i] != "" ? prov[i] : f)
			deps[target] = deps[target] " " ownname
		}
	}
	for (i = 1; i <= n; i++) visit(file[i])
	for (i = 1; i <= oc; i++) print olist[i]
}
function visit(node, dc, darr, k, target) {
	if (node in seen) return
	if (node in instack) {
		printf "rcorder: circular dependency at %s\n", node > "/dev/stderr"
		exit 1
	}
	instack[node] = 1
	dc = split(deps[node], darr, " ")
	for (k = 1; k <= dc; k++) {
		target = provides[darr[k]]
		if (target == "") continue
		visit(target)
	}
	delete instack[node]
	seen[node] = 1
	oc++
	olist[oc] = node
}
'
