#!/bin/sh
# Gets the system in a state ready for reboot/halt/poweroff.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if test $$ -ne 1; then
	echo "This program must be run as a continuation of init." >&2
	exit 1
fi
echo ": Sending SIGTERM to all processes"
kill -15 -1
sleep 3
echo ": Sending SIGKILL to remaining processes"
kill -9 -1
echo ": Syncing disks"
sync
echo ": Unmounting filesystems"
awk '{print $2}' /proc/mounts | sort -r | while read -r mntPath; do
	case $mntPath in
		"/"|"/proc"|"/sys"|"/dev"|"/dev/"*)
			continue
			;;
		*)
			umount $mntPath
			;;
	esac
done
echo ": Final sync"
sync
echo ": Remounting / as read-only"
mount -o remount,ro /
exec /usr/libexec/stage3stopsys $@
