#!/bin/sh
# Gets the system in a state ready for reboot/halt/poweroff.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.



# This function was written by AI, and the author has yet to be able to fully test it due to ongoing portability struggles.
# USE AT YOUR OWN RISK!
findMounts() {
	if test -r /proc/mounts; then
		# Linux
		awk '{print $2}' /proc/mounts
	elif test -r /etc/mnttab; then
		# Solaris/Illumos
		awk -F'\t' '{print $2}' /etc/mnttab
	else
		# BSDs
		mount | sed -n 's/^.* on \(.*\) (.*)$/\1/p'
	fi
}
if test $PPID -ne 1; then
	echo "This program must be directly invoked by init." >&2
	exit 1
fi

echo ": Syncing disks"
sync
echo ": Unmounting filesystems"
findMounts | awk '{print gsub(/\//,"/"), $0}' | sort -rn -k1,1 | cut -d' ' -f2- | while read -r mntPath; do
	case $mntPath in
		/ | /run | /proc | /sys | /dev | /dev/* | /kern)
			continue
			;;
		*)
			ATTEMPTS=5
			while test "$ATTEMPTS" -gt 0; do
				umount "$mntPath" 2> /dev/null
				if test "$?" -eq 0; then
					break
				fi
				sleep 1
				ATTEMPTS=$((ATTEMPTS-1))
			done
			if test "$ATTEMPTS" -eq 0; then
				echo >&2 "WARNING: $mntPath failed to unmount. This might have implications..."
			fi
			;;
	esac
done
echo ": Final sync"
sync
if test "$1" = "linux"; then
	echo ": Remounting / as read-only"
	ATTEMPTS=5
	while test "$ATTEMPTS" -gt 0; do
		mount -o remount,ro / 2> /dev/null
		if test "$?" -eq 0; then
			break
		fi
		ATTEMPTS=$((ATTEMPTS-1))
	done
	if test "$ATTEMPTS" -eq 0; then
		echo >&2 "FAIL: / didn't remount successfully. Continuing"
	fi
fi
