#!/bin/sh
# Sends a signal to init to begin the reboot/halt/poweroff process.

# Copyright (C) 2026 BLT Sandwich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PATH=/usr/sbin:/usr/bin:/sbin:/bin
if test $(id -u) -ne 0; then
	echo "This program must be run as root" >&2
	exit 1
fi
if test $$ -ne 1; then
	case $1 in
		"halt")
			echo "ALERT! System going down for halt NOW!" | wall -n
			kill -s USR2 1
			;;
		"shutdown")
			echo "ALERT! System going down for shutdown NOW!" | wall -n
			kill -s USR1 1
			;;
		"reboot")
			echo "ALERT! System going down for reboot NOW!" | wall -n
			kill -s INT 1
			;;
	esac
	case $0 in
		*"halt")
			wall -n "ALERT! System going down for halt NOW!"
			kill -s USR2 1
			;;
		*"shutdown"|*"poweroff")
			wall -n "ALERT! System going down for shutdown NOW!"
			kill -s USR1 1
			;;
		*"reboot")
			wall -n "ALERT! System going down for reboot NOW!"
			kill -s INT 1
			;;
	esac
fi
